/**
 * Presentation layer for the three prompt-status tiers (see migration 0016 and
 * the `PromptStatus` union in `@/types/domain`). This is the SINGLE source of
 * truth for every label, helper line, caveat, count label, and color used by
 * the badge, feed card, detail modal, canonical prompt page, filter surfaces,
 * and stats strip — so the trust language never drifts between them.
 *
 * Tailwind note: every className here is a complete literal string (no runtime
 * interpolation of color names), so the JIT compiler can see and emit them.
 */

import type { PromptStatus } from "@/types/domain";
import { isPromptStatus, DEFAULT_PROMPT_STATUS } from "@/types/domain";

export interface PromptStatusMeta {
  /** Full badge label, e.g. "Verified Prompt". */
  label: string;
  /** Short label for count chips, e.g. "Verified" / "References" / "Estimated". */
  countLabel: string;
  /** Section header above the prompt body, e.g. "Prompt" / "Estimated Prompt". */
  heading: string;
  /** One-line helper under the prompt-section header. */
  helper: string;
  /** Copy-button label. `null` means the tier is NOT copyable (reference). */
  copyLabel: string | null;
  /** Secondary caveat shown near the heading/empty-state. `null` when none. */
  caveat: string | null;
  /** Empty-state title when there is no prompt to show (reference only). */
  emptyTitle: string | null;
  /** Dot swatch — the only color the over-media (glass) badge carries. */
  dotClass: string;
  /** On-surface tinted pill: border + bg + text together. */
  tintedClass: string;
}

export const PROMPT_STATUS_META: Record<PromptStatus, PromptStatusMeta> = {
  verified: {
    label: "Verified Prompt",
    countLabel: "Verified",
    heading: "Prompt",
    helper: "Original prompt as shared from the source.",
    copyLabel: "Copy prompt",
    caveat: null,
    emptyTitle: null,
    dotClass: "bg-emerald-500",
    tintedClass: "border-emerald-500/30 bg-emerald-500/10 text-emerald-600",
  },
  reference: {
    label: "Visual Reference",
    countLabel: "References",
    heading: "Prompt",
    helper:
      "This creator did not share the original prompt. Save it as a visual reference or open the source.",
    copyLabel: null,
    caveat: "Not counted as a copyable prompt",
    emptyTitle: "Prompt not shared",
    dotClass: "bg-amber-500",
    tintedClass: "border-amber-500/30 bg-amber-500/10 text-amber-600",
  },
  estimated: {
    label: "Estimated Prompt",
    countLabel: "Estimated",
    heading: "Estimated Prompt",
    helper:
      "Generated by Feedlens from the image, not the creator's original prompt.",
    copyLabel: "Copy estimated prompt",
    caveat: "Approximate, not creator-verified",
    emptyTitle: null,
    dotClass: "bg-violet-500",
    tintedClass: "border-violet-500/30 bg-violet-500/10 text-violet-600",
  },
};

/** Narrow the DB's raw `prompt_status` text to a known tier (default verified). */
export function promptStatusOf(raw: string | null | undefined): PromptStatus {
  return isPromptStatus(raw) ? raw : DEFAULT_PROMPT_STATUS;
}
